### ISSUE TITLE
Need help with complining

### ISSUE THREAD

**Issue by tut32000** [0TheSpy/Seaside#3]
![image](https://user-images.githubusercontent.com/109449100/179383730-16045608-8df5-404e-8186-051b3b28e01c.png)
basically, i cant compline because of those warning and errors anyone has a solution for this.Tks

**Comment by Abir16x** [comment]
> ![image](https://user-images.githubusercontent.com/109449100/179383730-16045608-8df5-404e-8186-051b3b28e01c.png) basically, i cant compline because of those warning and errors anyone has a solution for this.Tks

bruh just download the DLL

**Comment by tut32000** [comment]
> > ![image](https://user-images.githubusercontent.com/109449100/179383730-16045608-8df5-404e-8186-051b3b28e01c.png) basically, i cant compline because of those warning and errors anyone has a solution for this.Tks
> 
> bruh just download the DLL
You don't understand man ,you will get low-trust factor if you use the vac bypass and if not you will get vac ban with the pure dll, i want to compline it in order to make it undetected as well as avoid low trust factor caused by vac-bypass

**Comment by 0TheSpy** [comment]
Microsoft DirectX SDK (June 2010) must be included 
https://www.microsoft.com/en-us/download/details.aspx?id=6812

DirectX SDK should be installed without errors. If "S1023" error appears, follow this tutorial:
https://support.microsoft.com/en-ca/help/2728613/s1023-error-when-you-install-the-directx-sdk-june-2010

HOW TO FIX C1083: Cannot open include file: 'd3dx9.h': No such file or directory:
Go to project properties -> VC++ Directories
and set "Include Directories" to "%your path here%\Microsoft DirectX SDK (June 2010)\Include"
and set "Library Directories" to "%your path here%\Microsoft DirectX SDK (June 2010)\Lib\x86"
